
banner:
  location: classpath:banner.txt
spring:
  application:
    name: monkey-seller
  datasources:
  - name: defaultTenant
    url: jdbc:mysql://monkey-dev-app.cch7wxaj6bgy.us-east-1.rds.amazonaws.com:3306/monkey_bill?zeroDateTimeBehavior=convertToNull
    username: admin_prd
    password: queiQu8i
    driver-class-name: com.mysql.jdbc.Driver
  - name: monkey-bill-monkeymkt
    url: jdbc:mysql://monkey-dev-app.cch7wxaj6bgy.us-east-1.rds.amazonaws.com:3306/monkeymkt_bill?zeroDateTimeBehavior=convertToNull&serverTimezone=GMT-3
    username: admin_prd
    password: queiQu8i
    driver-class-name: com.mysql.jdbc.Driver
